# NOTE: Changes to this config require removing ~/.cache/oh-my-posh for updates to take effect
console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  bg = '#1a1b26'
  bg_dark = '#16161e'
  bg_highlight = '#292e42'
  comment = '#565f89'
  subtle = '#737aa2'
  fg = '#c0caf5'
  red = '#f7768e'
  yellow = '#e0af68'
  orange = '#ff9e64'
  teal = '#73daca'
  cyan = '#7dcfff'
  purple = '#bb9af7'

[secondary_prompt]
  template = '❯❯ '
  foreground = 'p:subtle'

[transient_prompt]
  template = '❯ '
  foreground_templates = ['{{if gt .Code 0}}p:red{{end}}', '{{if eq .Code 0}}p:subtle{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{ .Path }}'
    foreground = 'p:cyan'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    template = ' {{ .HEAD }}{{if or .Working.Changed .Staging.Changed}}*{{end}}<p:teal>{{if gt .Behind 0}}⇣{{end}}{{if gt .Ahead 0}}⇡{{end}}</>'
    foreground = 'p:fg'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      fetch_status = true

  [[blocks.segments]]
    template = ' Py'
    foreground = 'p:yellow'
    type = 'python'
    style = 'plain'

    [blocks.segments.properties]
      fetch_virtual_env = true
      display_default = false

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    template = '{{ .FormattedMs }}'
    foreground = 'p:yellow'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = false

  [[blocks.segments]]
    template = ' ❯'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}p:red{{end}}', '{{if eq .Code 0}}p:subtle{{end}}']
