[general]
live_config_reload = true
import = [
  "~/.config/alacritty/theme.toml"
]

[env]
TERM = "xterm-256color"

[bell]
animation = "EaseOutExpo"
duration = 0

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

# Font size in points
size = 18.0
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
builtin_box_drawing = true

[colors]
draw_bold_text_with_bright_colors = true

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500
blink_timeout = 5
unfocused_hollow = true
thickness = 0.15

[mouse]
# Hide mouse cursor when typing
hide_when_typing = true

[hints]
# URL launcher
[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[keyboard]
bindings = [
    { key = "V", mods = "Command", action = "Paste" },
    { key = "C", mods = "Command", action = "Copy" },
    { key = "Q", mods = "Command", action = "Quit" },
    { key = "N", mods = "Command", action = "SpawnNewInstance" },
    { key = "W", mods = "Command", action = "Quit" },
    
    # Font size control,
    { key = "Plus", mods = "Command", action = "IncreaseFontSize" },
    { key = "Minus", mods = "Command", action = "DecreaseFontSize" },
    
    # Clear screen
    { key = "K", mods = "Command", chars = "\u000c" },
    
    # Search
    { key = "F", mods = "Command", action = "SearchForward" },
    
    # Fix Shift+Enter
    { key = "Return", mods = "Shift", chars = "\n" },
    
    # Toggle theme (Command+Option+Shift+T)
    { key = "T", mods = "Command|Option|Shift", command = { program = "/bin/bash", args = ["-c", "~/.config/alacritty/toggle-theme.sh"] } },
]

[scrolling]
history = 10000
multiplier = 3

[terminal]

[terminal.shell]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_title = true
option_as_alt = "OnlyRight"
dimensions = { columns = 140, lines = 40 }
padding = { x = 4, y = 4 }
dynamic_padding = true
startup_mode = "Windowed"
opacity = 1.0
decorations_theme_variant = "None"
