[colors.bright]
black = "#a8aecb"
blue = "#2e7de9"
cyan = "#007197"
green = "#587539"
magenta = "#9854f1"
red = "#f52a65"
white = "#3760bf"
yellow = "#8c6c3e"

[colors.normal]
black = "#a8aecb"
blue = "#2e7de9"
cyan = "#007197"
green = "#587539"
magenta = "#9854f1"
red = "#f52a65"
white = "#6172b0"
yellow = "#8c6c3e"

[colors.primary]
background = "#d5d6db"
foreground = "#3760bf"
